-- Creation of AIRLINE table
CREATE TABLE AIRLINE (
    AIRLINE_CODE VARCHAR2(10) PRIMARY KEY,
    AIRLINE_NAME VARCHAR2(100) NOT NULL,
    HEADQUARTERS VARCHAR2(100)
);

-- Creation of AIRCRAFT table
CREATE TABLE AIRCRAFT (
    AIRCRAFT_ID VARCHAR2(20) PRIMARY KEY,
    TAIL_NUMBER VARCHAR2(20) NOT NULL,
    MODEL VARCHAR2(50) NOT NULL,
    CAPACITY NUMBER NOT NULL
);

-- Creation of AIRPORT table
CREATE TABLE AIRPORT (
    AIRPORT_CODE VARCHAR2(10) PRIMARY KEY,
    AIRPORT_NAME VARCHAR2(100) NOT NULL,
    CITY VARCHAR2(50) NOT NULL,
    STATE VARCHAR2(50) NOT NULL,
    COUNTRY VARCHAR2(50) NOT NULL,
    TIMEZONE VARCHAR2(50) NOT NULL,
    LATITUDE NUMBER(9,6),
    LONGITUDE NUMBER(9,6)
);

-- Creation of ROUTE table
CREATE TABLE ROUTE (
    ROUTE_ID VARCHAR2(20) PRIMARY KEY,
    ORIGIN_AIRPORT VARCHAR2(10) NOT NULL,
    DESTINATION_AIRPORT VARCHAR2(10) NOT NULL,
    DISTANCE NUMBER,
    CONSTRAINT FK_ROUTE_ORIGIN FOREIGN KEY (ORIGIN_AIRPORT) REFERENCES AIRPORT(AIRPORT_CODE),
    CONSTRAINT FK_ROUTE_DESTINATION FOREIGN KEY (DESTINATION_AIRPORT) REFERENCES AIRPORT(AIRPORT_CODE)
);

-- Creation of FLIGHT table
CREATE TABLE FLIGHT (
    FLIGHT_ID VARCHAR2(20) PRIMARY KEY,
    FLIGHT_NUMBER NUMBER NOT NULL,
    AIRLINE_CODE VARCHAR2(10) NOT NULL,
    ROUTE_ID VARCHAR2(20) NOT NULL,
    AIRCRAFT_ID VARCHAR2(20) NOT NULL,
    DEPARTURE_TIME TIMESTAMP NOT NULL,
    ARRIVAL_TIME TIMESTAMP,
    STATUS VARCHAR2(30) NOT NULL,
    CONSTRAINT FK_FLIGHT_AIRLINE FOREIGN KEY (AIRLINE_CODE) REFERENCES AIRLINE(AIRLINE_CODE),
    CONSTRAINT FK_FLIGHT_ROUTE FOREIGN KEY (ROUTE_ID) REFERENCES ROUTE(ROUTE_ID),
    CONSTRAINT FK_FLIGHT_AIRCRAFT FOREIGN KEY (AIRCRAFT_ID) REFERENCES AIRCRAFT(AIRCRAFT_ID)
);

-- Creation of FLIGHT_DELAY table
CREATE TABLE FLIGHT_DELAY (
    FLIGHT_ID VARCHAR2(20),
    DELAY_SEQUENCE NUMBER,
    DELAY_TYPE VARCHAR2(50) NOT NULL,
    DELAY_MINUTES NUMBER NOT NULL,
    CONSTRAINT PK_FLIGHT_DELAY PRIMARY KEY (FLIGHT_ID, DELAY_SEQUENCE),
    CONSTRAINT FK_DELAY_FLIGHT FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHT(FLIGHT_ID)
);